package org.jmisb.api.klv.st1108.st1108_2;

import static org.testng.Assert.*;

import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import org.jmisb.api.common.KlvParseException;
import org.jmisb.api.klv.BerDecoder;
import org.jmisb.api.klv.BerField;
import org.jmisb.api.klv.IKlvValue;
import org.jmisb.api.klv.KlvConstants;
import org.jmisb.api.klv.LdsField;
import org.jmisb.api.klv.LdsParser;
import org.jmisb.api.klv.LoggerChecks;
import org.jmisb.api.klv.UniversalLabel;
import org.jmisb.api.klv.st0603.ST0603TimeStamp;
import org.jmisb.api.klv.st1108.IInterpretabilityQualityMetadataValue;
import org.testng.annotations.Test;

/** Tests for the (legacy) ST 1108.2 Interpretability and Quality Local Set. */
public class LegacyIQLocalSetTest extends LoggerChecks {
    LegacyIQLocalSetTest() {
        super(LegacyIQLocalSet.class);
    }

    private static List<LdsField> getFields(final byte[] bytes)
            throws IllegalArgumentException, KlvParseException {
        int offset = UniversalLabel.LENGTH;
        BerField len = BerDecoder.decode(bytes, offset, false);
        offset += len.getLength();
        List<LdsField> fields = LdsParser.parseFields(bytes, offset, len.getValue());
        return fields;
    }

    @Test
    public void fromUnknownTag() throws KlvParseException {
        byte[] bytes =
                new byte[] {
                    0x06, 0x0E, 0x2B, 0x34, 0x02, 0x03, 0x01, 0x01, 0x0E, 0x01, 0x03, 0x03, 0x1C,
                    0x00, 0x00, 0x00, 0x03, 0x7F, 0x01, 0x00,
                };
        List<LdsField> fields = getFields(bytes);
        verifyNoLoggerMessages();
        LegacyIQLocalSet.fromST1108_2Fields(fields, bytes);
        verifySingleLoggerMessage("Unknown Legacy Interpretability and Quality Metadata tag: 127");
    }

    private final byte[] manyTagsBytes =
            new byte[] {
                0x06,
                0x0E,
                0x2B,
                0x34,
                0x02,
                0x03,
                0x01,
                0x01,
                0x0E,
                0x01,
                0x03,
                0x03,
                0x1C,
                0x00,
                0x00,
                0x00,
                (byte) 0x82,
                (byte) 0x05,
                (byte) 0x88,
                0x01,
                0x08,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x09,
                0x02,
                0x01,
                (byte) 0x06,
                0x03,
                0x01,
                (byte) 0x60,
                0x04,
                0x01,
                (byte) 0x00,
                0x05,
                0x01,
                (byte) 0x02,
                0x06,
                0x01,
                (byte) 0x04,
                0x07,
                0x02,
                (byte) 0x02,
                (byte) 0x80,
                0x08,
                0x08,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x00,
                (byte) 0x20,
                0x09,
                0x08,
                (byte) 0x00,
                (byte) 0x57,
                (byte) 0x01,
                (byte) 0x5a,
                (byte) 0x00,
                (byte) 0x20,
                (byte) 0x00,
                (byte) 0x08,
                0x0a,
                (byte) 0x82,
                0x04,
                0x00,
                (byte) 0x00,
                (byte) 0x01,
                (byte) 0x02,
                (byte) 0x03,
                (byte) 0x04,
                (byte) 0x05,
                (byte) 0x06,
                (byte) 0x07,
                (byte) 0x08,
                (byte) 0x09,
                (byte) 0x0a,
                (byte) 0x0b,
                (byte) 0x0c,
                (byte) 0x0d,
                (byte) 0x0e,
                (byte) 0x0f,
                (byte) 0x10,
                (byte) 0x11,
                (byte) 0x12,
                (byte) 0x13,
                (byte) 0x14,
                (byte) 0x15,
                (byte) 0x16,
                (byte) 0x17,
                (byte) 0x18,
                (byte) 0x19,
                (byte) 0x1a,
                (byte) 0x1b,
                (byte) 0x1c,
                (byte) 0x1d,
                (byte) 0x1e,
                (byte) 0x1f,
                (byte) 0x20,
                (byte) 0x21,
                (byte) 0x22,
                (byte) 0x23,
                (byte) 0x24,
                (byte) 0x25,
                (byte) 0x26,
                (byte) 0x27,
                (byte) 0x28,
                (byte) 0x29,
                (byte) 0x2a,
                (byte) 0x2b,
                (byte) 0x2c,
                (byte) 0x2d,
                (byte) 0x2e,
                (byte) 0x2f,
                (byte) 0x30,
                (byte) 0x31,
                (byte) 0x32,
                (byte) 0x33,
                (byte) 0x34,
                (byte) 0x35,
                (byte) 0x36,
                (byte) 0x37,
                (byte) 0x38,
                (byte) 0x39,
                (byte) 0x3a,
                (byte) 0x3b,
                (byte) 0x3c,
                (byte) 0x3d,
                (byte) 0x3e,
                (byte) 0x3f,
                (byte) 0x40,
                (byte) 0x41,
                (byte) 0x42,
                (byte) 0x43,
                (byte) 0x44,
                (byte) 0x45,
                (byte) 0x46,
                (byte) 0x47,
                (byte) 0x48,
                (byte) 0x49,
                (byte) 0x4a,
                (byte) 0x4b,
                (byte) 0x4c,
                (byte) 0x4d,
                (byte) 0x4e,
                (byte) 0x4f,
                (byte) 0x50,
                (byte) 0x51,
                (byte) 0x52,
                (byte) 0x53,
                (byte) 0x54,
                (byte) 0x55,
                (byte) 0x56,
                (byte) 0x57,
                (byte) 0x58,
                (byte) 0x59,
                (byte) 0x5a,
                (byte) 0x5b,
                (byte) 0x5c,
                (byte) 0x5d,
                (byte) 0x5e,
                (byte) 0x5f,
                (byte) 0x60,
                (byte) 0x61,
                (byte) 0x62,
                (byte) 0x63,
                (byte) 0x64,
                (byte) 0x65,
                (byte) 0x66,
                (byte) 0x67,
                (byte) 0x68,
                (byte) 0x69,
                (byte) 0x6a,
                (byte) 0x6b,
                (byte) 0x6c,
                (byte) 0x6d,
                (byte) 0x6e,
                (byte) 0x6f,
                (byte) 0x70,
                (byte) 0x71,
                (byte) 0x72,
                (byte) 0x73,
                (byte) 0x74,
                (byte) 0x75,
                (byte) 0x76,
                (byte) 0x77,
                (byte) 0x78,
                (byte) 0x79,
                (byte) 0x7a,
                (byte) 0x7b,
                (byte) 0x7c,
                (byte) 0x7d,
                (byte) 0x7e,
                (byte) 0x7f,
                (byte) 0x80,
                (byte) 0x81,
                (byte) 0x82,
                (byte) 0x83,
                (byte) 0x84,
                (byte) 0x85,
                (byte) 0x86,
                (byte) 0x87,
                (byte) 0x88,
                (byte) 0x89,
                (byte) 0x8a,
                (byte) 0x8b,
                (byte) 0x8c,
                (byte) 0x8d,
                (byte) 0x8e,
                (byte) 0x8f,
                (byte) 0x90,
                (byte) 0x91,
                (byte) 0x92,
                (byte) 0x93,
                (byte) 0x94,
                (byte) 0x95,
                (byte) 0x96,
                (byte) 0x97,
                (byte) 0x98,
                (byte) 0x99,
                (byte) 0x9a,
                (byte) 0x9b,
                (byte) 0x9c,
                (byte) 0x9d,
                (byte) 0x9e,
                (byte) 0x9f,
                (byte) 0xa0,
                (byte) 0xa1,
                (byte) 0xa2,
                (byte) 0xa3,
                (byte) 0xa4,
                (byte) 0xa5,
                (byte) 0xa6,
                (byte) 0xa7,
                (byte) 0xa8,
                (byte) 0xa9,
                (byte) 0xaa,
                (byte) 0xab,
                (byte) 0xac,
                (byte) 0xad,
                (byte) 0xae,
                (byte) 0xaf,
                (byte) 0xb0,
                (byte) 0xb1,
                (byte) 0xb2,
                (byte) 0xb3,
                (byte) 0xb4,
                (byte) 0xb5,
                (byte) 0xb6,
                (byte) 0xb7,
                (byte) 0xb8,
                (byte) 0xb9,
                (byte) 0xba,
                (byte) 0xbb,
                (byte) 0xbc,
                (byte) 0xbd,
                (byte) 0xbe,
                (byte) 0xbf,
                (byte) 0xc0,
                (byte) 0xc1,
                (byte) 0xc2,
                (byte) 0xc3,
                (byte) 0xc4,
                (byte) 0xc5,
                (byte) 0xc6,
                (byte) 0xc7,
                (byte) 0xc8,
                (byte) 0xc9,
                (byte) 0xca,
                (byte) 0xcb,
                (byte) 0xcc,
                (byte) 0xcd,
                (byte) 0xce,
                (byte) 0xcf,
                (byte) 0xd0,
                (byte) 0xd1,
                (byte) 0xd2,
                (byte) 0xd3,
                (byte) 0xd4,
                (byte) 0xd5,
                (byte) 0xd6,
                (byte) 0xd7,
                (byte) 0xd8,
                (byte) 0xd9,
                (byte) 0xda,
                (byte) 0xdb,
                (byte) 0xdc,
                (byte) 0xdd,
                (byte) 0xde,
                (byte) 0xdf,
                (byte) 0xe0,
                (byte) 0xe1,
                (byte) 0xe2,
                (byte) 0xe3,
                (byte) 0xe4,
                (byte) 0xe5,
                (byte) 0xe6,
                (byte) 0xe7,
                (byte) 0xe8,
                (byte) 0xe9,
                (byte) 0xea,
                (byte) 0xeb,
                (byte) 0xec,
                (byte) 0xed,
                (byte) 0xee,
                (byte) 0xef,
                (byte) 0xf0,
                (byte) 0xf1,
                (byte) 0xf2,
                (byte) 0xf3,
                (byte) 0xf4,
                (byte) 0xf5,
                (byte) 0xf6,
                (byte) 0xf7,
                (byte) 0xf8,
                (byte) 0xf9,
                (byte) 0xfa,
                (byte) 0xfb,
                (byte) 0xfc,
                (byte) 0xfd,
                (byte) 0xfe,
                (byte) 0xff,
                (byte) 0x00,
                (byte) 0x01,
                (byte) 0x02,
                (byte) 0x03,
                (byte) 0x04,
                (byte) 0x05,
                (byte) 0x06,
                (byte) 0x07,
                (byte) 0x08,
                (byte) 0x09,
                (byte) 0x0a,
                (byte) 0x0b,
                (byte) 0x0c,
                (byte) 0x0d,
                (byte) 0x0e,
                (byte) 0x0f,
                (byte) 0x10,
                (byte) 0x11,
                (byte) 0x12,
                (byte) 0x13,
                (byte) 0x14,
                (byte) 0x15,
                (byte) 0x16,
                (byte) 0x17,
                (byte) 0x18,
                (byte) 0x19,
                (byte) 0x1a,
                (byte) 0x1b,
                (byte) 0x1c,
                (byte) 0x1d,
                (byte) 0x1e,
                (byte) 0x1f,
                (byte) 0x20,
                (byte) 0x21,
                (byte) 0x22,
                (byte) 0x23,
                (byte) 0x24,
                (byte) 0x25,
                (byte) 0x26,
                (byte) 0x27,
                (byte) 0x28,
                (byte) 0x29,
                (byte) 0x2a,
                (byte) 0x2b,
                (byte) 0x2c,
                (byte) 0x2d,
                (byte) 0x2e,
                (byte) 0x2f,
                (byte) 0x30,
                (byte) 0x31,
                (byte) 0x32,
                (byte) 0x33,
                (byte) 0x34,
                (byte) 0x35,
                (byte) 0x36,
                (byte) 0x37,
                (byte) 0x38,
                (byte) 0x39,
                (byte) 0x3a,
                (byte) 0x3b,
                (byte) 0x3c,
                (byte) 0x3d,
                (byte) 0x3e,
                (byte) 0x3f,
                (byte) 0x40,
                (byte) 0x41,
                (byte) 0x42,
                (byte) 0x43,
                (byte) 0x44,
                (byte) 0x45,
                (byte) 0x46,
                (byte) 0x47,
                (byte) 0x48,
                (byte) 0x49,
                (byte) 0x4a,
                (byte) 0x4b,
                (byte) 0x4c,
                (byte) 0x4d,
                (byte) 0x4e,
                (byte) 0x4f,
                (byte) 0x50,
                (byte) 0x51,
                (byte) 0x52,
                (byte) 0x53,
                (byte) 0x54,
                (byte) 0x55,
                (byte) 0x56,
                (byte) 0x57,
                (byte) 0x58,
                (byte) 0x59,
                (byte) 0x5a,
                (byte) 0x5b,
                (byte) 0x5c,
                (byte) 0x5d,
                (byte) 0x5e,
                (byte) 0x5f,
                (byte) 0x60,
                (byte) 0x61,
                (byte) 0x62,
                (byte) 0x63,
                (byte) 0x64,
                (byte) 0x65,
                (byte) 0x66,
                (byte) 0x67,
                (byte) 0x68,
                (byte) 0x69,
                (byte) 0x6a,
                (byte) 0x6b,
                (byte) 0x6c,
                (byte) 0x6d,
                (byte) 0x6e,
                (byte) 0x6f,
                (byte) 0x70,
                (byte) 0x71,
                (byte) 0x72,
                (byte) 0x73,
                (byte) 0x74,
                (byte) 0x75,
                (byte) 0x76,
                (byte) 0x77,
                (byte) 0x78,
                (byte) 0x79,
                (byte) 0x7a,
                (byte) 0x7b,
                (byte) 0x7c,
                (byte) 0x7d,
                (byte) 0x7e,
                (byte) 0x7f,
                (byte) 0x80,
                (byte) 0x81,
                (byte) 0x82,
                (byte) 0x83,
                (byte) 0x84,
                (byte) 0x85,
                (byte) 0x86,
                (byte) 0x87,
                (byte) 0x88,
                (byte) 0x89,
                (byte) 0x8a,
                (byte) 0x8b,
                (byte) 0x8c,
                (byte) 0x8d,
                (byte) 0x8e,
                (byte) 0x8f,
                (byte) 0x90,
                (byte) 0x91,
                (byte) 0x92,
                (byte) 0x93,
                (byte) 0x94,
                (byte) 0x95,
                (byte) 0x96,
                (byte) 0x97,
                (byte) 0x98,
                (byte) 0x99,
                (byte) 0x9a,
                (byte) 0x9b,
                (byte) 0x9c,
                (byte) 0x9d,
                (byte) 0x9e,
                (byte) 0x9f,
                (byte) 0xa0,
                (byte) 0xa1,
                (byte) 0xa2,
                (byte) 0xa3,
                (byte) 0xa4,
                (byte) 0xa5,
                (byte) 0xa6,
                (byte) 0xa7,
                (byte) 0xa8,
                (byte) 0xa9,
                (byte) 0xaa,
                (byte) 0xab,
                (byte) 0xac,
                (byte) 0xad,
                (byte) 0xae,
                (byte) 0xaf,
                (byte) 0xb0,
                (byte) 0xb1,
                (byte) 0xb2,
                (byte) 0xb3,
                (byte) 0xb4,
                (byte) 0xb5,
                (byte) 0xb6,
                (byte) 0xb7,
                (byte) 0xb8,
                (byte) 0xb9,
                (byte) 0xba,
                (byte) 0xbb,
                (byte) 0xbc,
                (byte) 0xbd,
                (byte) 0xbe,
                (byte) 0xbf,
                (byte) 0xc0,
                (byte) 0xc1,
                (byte) 0xc2,
                (byte) 0xc3,
                (byte) 0xc4,
                (byte) 0xc5,
                (byte) 0xc6,
                (byte) 0xc7,
                (byte) 0xc8,
                (byte) 0xc9,
                (byte) 0xca,
                (byte) 0xcb,
                (byte) 0xcc,
                (byte) 0xcd,
                (byte) 0xce,
                (byte) 0xcf,
                (byte) 0xd0,
                (byte) 0xd1,
                (byte) 0xd2,
                (byte) 0xd3,
                (byte) 0xd4,
                (byte) 0xd5,
                (byte) 0xd6,
                (byte) 0xd7,
                (byte) 0xd8,
                (byte) 0xd9,
                (byte) 0xda,
                (byte) 0xdb,
                (byte) 0xdc,
                (byte) 0xdd,
                (byte) 0xde,
                (byte) 0xdf,
                (byte) 0xe0,
                (byte) 0xe1,
                (byte) 0xe2,
                (byte) 0xe3,
                (byte) 0xe4,
                (byte) 0xe5,
                (byte) 0xe6,
                (byte) 0xe7,
                (byte) 0xe8,
                (byte) 0xe9,
                (byte) 0xea,
                (byte) 0xeb,
                (byte) 0xec,
                (byte) 0xed,
                (byte) 0xee,
                (byte) 0xef,
                (byte) 0xf0,
                (byte) 0xf1,
                (byte) 0xf2,
                (byte) 0xf3,
                (byte) 0xf4,
                (byte) 0xf5,
                (byte) 0xf6,
                (byte) 0xf7,
                (byte) 0xf8,
                (byte) 0xf9,
                (byte) 0xfa,
                (byte) 0xfb,
                (byte) 0xfc,
                (byte) 0xfd,
                (byte) 0xfe,
                (byte) 0xff,
                (byte) 0x00,
                (byte) 0x01,
                (byte) 0x02,
                (byte) 0x03,
                (byte) 0x04,
                (byte) 0x05,
                (byte) 0x06,
                (byte) 0x07,
                (byte) 0x08,
                (byte) 0x09,
                (byte) 0x0a,
                (byte) 0x0b,
                (byte) 0x0c,
                (byte) 0x0d,
                (byte) 0x0e,
                (byte) 0x0f,
                (byte) 0x10,
                (byte) 0x11,
                (byte) 0x12,
                (byte) 0x13,
                (byte) 0x14,
                (byte) 0x15,
                (byte) 0x16,
                (byte) 0x17,
                (byte) 0x18,
                (byte) 0x19,
                (byte) 0x1a,
                (byte) 0x1b,
                (byte) 0x1c,
                (byte) 0x1d,
                (byte) 0x1e,
                (byte) 0x1f,
                (byte) 0x20,
                (byte) 0x21,
                (byte) 0x22,
                (byte) 0x23,
                (byte) 0x24,
                (byte) 0x25,
                (byte) 0x26,
                (byte) 0x27,
                (byte) 0x28,
                (byte) 0x29,
                (byte) 0x2a,
                (byte) 0x2b,
                (byte) 0x2c,
                (byte) 0x2d,
                (byte) 0x2e,
                (byte) 0x2f,
                (byte) 0x30,
                (byte) 0x31,
                (byte) 0x32,
                (byte) 0x33,
                (byte) 0x34,
                (byte) 0x35,
                (byte) 0x36,
                (byte) 0x37,
                (byte) 0x38,
                (byte) 0x39,
                (byte) 0x3a,
                (byte) 0x3b,
                (byte) 0x3c,
                (byte) 0x3d,
                (byte) 0x3e,
                (byte) 0x3f,
                (byte) 0x40,
                (byte) 0x41,
                (byte) 0x42,
                (byte) 0x43,
                (byte) 0x44,
                (byte) 0x45,
                (byte) 0x46,
                (byte) 0x47,
                (byte) 0x48,
                (byte) 0x49,
                (byte) 0x4a,
                (byte) 0x4b,
                (byte) 0x4c,
                (byte) 0x4d,
                (byte) 0x4e,
                (byte) 0x4f,
                (byte) 0x50,
                (byte) 0x51,
                (byte) 0x52,
                (byte) 0x53,
                (byte) 0x54,
                (byte) 0x55,
                (byte) 0x56,
                (byte) 0x57,
                (byte) 0x58,
                (byte) 0x59,
                (byte) 0x5a,
                (byte) 0x5b,
                (byte) 0x5c,
                (byte) 0x5d,
                (byte) 0x5e,
                (byte) 0x5f,
                (byte) 0x60,
                (byte) 0x61,
                (byte) 0x62,
                (byte) 0x63,
                (byte) 0x64,
                (byte) 0x65,
                (byte) 0x66,
                (byte) 0x67,
                (byte) 0x68,
                (byte) 0x69,
                (byte) 0x6a,
                (byte) 0x6b,
                (byte) 0x6c,
                (byte) 0x6d,
                (byte) 0x6e,
                (byte) 0x6f,
                (byte) 0x70,
                (byte) 0x71,
                (byte) 0x72,
                (byte) 0x73,
                (byte) 0x74,
                (byte) 0x75,
                (byte) 0x76,
                (byte) 0x77,
                (byte) 0x78,
                (byte) 0x79,
                (byte) 0x7a,
                (byte) 0x7b,
                (byte) 0x7c,
                (byte) 0x7d,
                (byte) 0x7e,
                (byte) 0x7f,
                (byte) 0x80,
                (byte) 0x81,
                (byte) 0x82,
                (byte) 0x83,
                (byte) 0x84,
                (byte) 0x85,
                (byte) 0x86,
                (byte) 0x87,
                (byte) 0x88,
                (byte) 0x89,
                (byte) 0x8a,
                (byte) 0x8b,
                (byte) 0x8c,
                (byte) 0x8d,
                (byte) 0x8e,
                (byte) 0x8f,
                (byte) 0x90,
                (byte) 0x91,
                (byte) 0x92,
                (byte) 0x93,
                (byte) 0x94,
                (byte) 0x95,
                (byte) 0x96,
                (byte) 0x97,
                (byte) 0x98,
                (byte) 0x99,
                (byte) 0x9a,
                (byte) 0x9b,
                (byte) 0x9c,
                (byte) 0x9d,
                (byte) 0x9e,
                (byte) 0x9f,
                (byte) 0xa0,
                (byte) 0xa1,
                (byte) 0xa2,
                (byte) 0xa3,
                (byte) 0xa4,
                (byte) 0xa5,
                (byte) 0xa6,
                (byte) 0xa7,
                (byte) 0xa8,
                (byte) 0xa9,
                (byte) 0xaa,
                (byte) 0xab,
                (byte) 0xac,
                (byte) 0xad,
                (byte) 0xae,
                (byte) 0xaf,
                (byte) 0xb0,
                (byte) 0xb1,
                (byte) 0xb2,
                (byte) 0xb3,
                (byte) 0xb4,
                (byte) 0xb5,
                (byte) 0xb6,
                (byte) 0xb7,
                (byte) 0xb8,
                (byte) 0xb9,
                (byte) 0xba,
                (byte) 0xbb,
                (byte) 0xbc,
                (byte) 0xbd,
                (byte) 0xbe,
                (byte) 0xbf,
                (byte) 0xc0,
                (byte) 0xc1,
                (byte) 0xc2,
                (byte) 0xc3,
                (byte) 0xc4,
                (byte) 0xc5,
                (byte) 0xc6,
                (byte) 0xc7,
                (byte) 0xc8,
                (byte) 0xc9,
                (byte) 0xca,
                (byte) 0xcb,
                (byte) 0xcc,
                (byte) 0xcd,
                (byte) 0xce,
                (byte) 0xcf,
                (byte) 0xd0,
                (byte) 0xd1,
                (byte) 0xd2,
                (byte) 0xd3,
                (byte) 0xd4,
                (byte) 0xd5,
                (byte) 0xd6,
                (byte) 0xd7,
                (byte) 0xd8,
                (byte) 0xd9,
                (byte) 0xda,
                (byte) 0xdb,
                (byte) 0xdc,
                (byte) 0xdd,
                (byte) 0xde,
                (byte) 0xdf,
                (byte) 0xe0,
                (byte) 0xe1,
                (byte) 0xe2,
                (byte) 0xe3,
                (byte) 0xe4,
                (byte) 0xe5,
                (byte) 0xe6,
                (byte) 0xe7,
                (byte) 0xe8,
                (byte) 0xe9,
                (byte) 0xea,
                (byte) 0xeb,
                (byte) 0xec,
                (byte) 0xed,
                (byte) 0xee,
                (byte) 0xef,
                (byte) 0xf0,
                (byte) 0xf1,
                (byte) 0xf2,
                (byte) 0xf3,
                (byte) 0xf4,
                (byte) 0xf5,
                (byte) 0xf6,
                (byte) 0xf7,
                (byte) 0xf8,
                (byte) 0xf9,
                (byte) 0xfa,
                (byte) 0xfb,
                (byte) 0xfc,
                (byte) 0xfd,
                (byte) 0xfe,
                (byte) 0xff,
                (byte) 0x00,
                (byte) 0x01,
                (byte) 0x02,
                (byte) 0x03,
                (byte) 0x04,
                (byte) 0x05,
                (byte) 0x06,
                (byte) 0x07,
                (byte) 0x08,
                (byte) 0x09,
                (byte) 0x0a,
                (byte) 0x0b,
                (byte) 0x0c,
                (byte) 0x0d,
                (byte) 0x0e,
                (byte) 0x0f,
                (byte) 0x10,
                (byte) 0x11,
                (byte) 0x12,
                (byte) 0x13,
                (byte) 0x14,
                (byte) 0x15,
                (byte) 0x16,
                (byte) 0x17,
                (byte) 0x18,
                (byte) 0x19,
                (byte) 0x1a,
                (byte) 0x1b,
                (byte) 0x1c,
                (byte) 0x1d,
                (byte) 0x1e,
                (byte) 0x1f,
                (byte) 0x20,
                (byte) 0x21,
                (byte) 0x22,
                (byte) 0x23,
                (byte) 0x24,
                (byte) 0x25,
                (byte) 0x26,
                (byte) 0x27,
                (byte) 0x28,
                (byte) 0x29,
                (byte) 0x2a,
                (byte) 0x2b,
                (byte) 0x2c,
                (byte) 0x2d,
                (byte) 0x2e,
                (byte) 0x2f,
                (byte) 0x30,
                (byte) 0x31,
                (byte) 0x32,
                (byte) 0x33,
                (byte) 0x34,
                (byte) 0x35,
                (byte) 0x36,
                (byte) 0x37,
                (byte) 0x38,
                (byte) 0x39,
                (byte) 0x3a,
                (byte) 0x3b,
                (byte) 0x3c,
                (byte) 0x3d,
                (byte) 0x3e,
                (byte) 0x3f,
                (byte) 0x40,
                (byte) 0x41,
                (byte) 0x42,
                (byte) 0x43,
                (byte) 0x44,
                (byte) 0x45,
                (byte) 0x46,
                (byte) 0x47,
                (byte) 0x48,
                (byte) 0x49,
                (byte) 0x4a,
                (byte) 0x4b,
                (byte) 0x4c,
                (byte) 0x4d,
                (byte) 0x4e,
                (byte) 0x4f,
                (byte) 0x50,
                (byte) 0x51,
                (byte) 0x52,
                (byte) 0x53,
                (byte) 0x54,
                (byte) 0x55,
                (byte) 0x56,
                (byte) 0x57,
                (byte) 0x58,
                (byte) 0x59,
                (byte) 0x5a,
                (byte) 0x5b,
                (byte) 0x5c,
                (byte) 0x5d,
                (byte) 0x5e,
                (byte) 0x5f,
                (byte) 0x60,
                (byte) 0x61,
                (byte) 0x62,
                (byte) 0x63,
                (byte) 0x64,
                (byte) 0x65,
                (byte) 0x66,
                (byte) 0x67,
                (byte) 0x68,
                (byte) 0x69,
                (byte) 0x6a,
                (byte) 0x6b,
                (byte) 0x6c,
                (byte) 0x6d,
                (byte) 0x6e,
                (byte) 0x6f,
                (byte) 0x70,
                (byte) 0x71,
                (byte) 0x72,
                (byte) 0x73,
                (byte) 0x74,
                (byte) 0x75,
                (byte) 0x76,
                (byte) 0x77,
                (byte) 0x78,
                (byte) 0x79,
                (byte) 0x7a,
                (byte) 0x7b,
                (byte) 0x7c,
                (byte) 0x7d,
                (byte) 0x7e,
                (byte) 0x7f,
                (byte) 0x80,
                (byte) 0x81,
                (byte) 0x82,
                (byte) 0x83,
                (byte) 0x84,
                (byte) 0x85,
                (byte) 0x86,
                (byte) 0x87,
                (byte) 0x88,
                (byte) 0x89,
                (byte) 0x8a,
                (byte) 0x8b,
                (byte) 0x8c,
                (byte) 0x8d,
                (byte) 0x8e,
                (byte) 0x8f,
                (byte) 0x90,
                (byte) 0x91,
                (byte) 0x92,
                (byte) 0x93,
                (byte) 0x94,
                (byte) 0x95,
                (byte) 0x96,
                (byte) 0x97,
                (byte) 0x98,
                (byte) 0x99,
                (byte) 0x9a,
                (byte) 0x9b,
                (byte) 0x9c,
                (byte) 0x9d,
                (byte) 0x9e,
                (byte) 0x9f,
                (byte) 0xa0,
                (byte) 0xa1,
                (byte) 0xa2,
                (byte) 0xa3,
                (byte) 0xa4,
                (byte) 0xa5,
                (byte) 0xa6,
                (byte) 0xa7,
                (byte) 0xa8,
                (byte) 0xa9,
                (byte) 0xaa,
                (byte) 0xab,
                (byte) 0xac,
                (byte) 0xad,
                (byte) 0xae,
                (byte) 0xaf,
                (byte) 0xb0,
                (byte) 0xb1,
                (byte) 0xb2,
                (byte) 0xb3,
                (byte) 0xb4,
                (byte) 0xb5,
                (byte) 0xb6,
                (byte) 0xb7,
                (byte) 0xb8,
                (byte) 0xb9,
                (byte) 0xba,
                (byte) 0xbb,
                (byte) 0xbc,
                (byte) 0xbd,
                (byte) 0xbe,
                (byte) 0xbf,
                (byte) 0xc0,
                (byte) 0xc1,
                (byte) 0xc2,
                (byte) 0xc3,
                (byte) 0xc4,
                (byte) 0xc5,
                (byte) 0xc6,
                (byte) 0xc7,
                (byte) 0xc8,
                (byte) 0xc9,
                (byte) 0xca,
                (byte) 0xcb,
                (byte) 0xcc,
                (byte) 0xcd,
                (byte) 0xce,
                (byte) 0xcf,
                (byte) 0xd0,
                (byte) 0xd1,
                (byte) 0xd2,
                (byte) 0xd3,
                (byte) 0xd4,
                (byte) 0xd5,
                (byte) 0xd6,
                (byte) 0xd7,
                (byte) 0xd8,
                (byte) 0xd9,
                (byte) 0xda,
                (byte) 0xdb,
                (byte) 0xdc,
                (byte) 0xdd,
                (byte) 0xde,
                (byte) 0xdf,
                (byte) 0xe0,
                (byte) 0xe1,
                (byte) 0xe2,
                (byte) 0xe3,
                (byte) 0xe4,
                (byte) 0xe5,
                (byte) 0xe6,
                (byte) 0xe7,
                (byte) 0xe8,
                (byte) 0xe9,
                (byte) 0xea,
                (byte) 0xeb,
                (byte) 0xec,
                (byte) 0xed,
                (byte) 0xee,
                (byte) 0xef,
                (byte) 0xf0,
                (byte) 0xf1,
                (byte) 0xf2,
                (byte) 0xf3,
                (byte) 0xf4,
                (byte) 0xf5,
                (byte) 0xf6,
                (byte) 0xf7,
                (byte) 0xf8,
                (byte) 0xf9,
                (byte) 0xfa,
                (byte) 0xfb,
                (byte) 0xfc,
                (byte) 0xfd,
                (byte) 0xfe,
                (byte) 0xff,
                0x0b,
                (byte) 0x82,
                0x01,
                0x44,
                (byte) 0x00,
                (byte) 0x01,
                (byte) 0x02,
                (byte) 0x03,
                (byte) 0x04,
                (byte) 0x05,
                (byte) 0x06,
                (byte) 0x07,
                (byte) 0x08,
                (byte) 0x09,
                (byte) 0x0a,
                (byte) 0x0b,
                (byte) 0x0c,
                (byte) 0x0d,
                (byte) 0x0e,
                (byte) 0x0f,
                (byte) 0x10,
                (byte) 0x11,
                (byte) 0x12,
                (byte) 0x13,
                (byte) 0x14,
                (byte) 0x15,
                (byte) 0x16,
                (byte) 0x17,
                (byte) 0x18,
                (byte) 0x19,
                (byte) 0x1a,
                (byte) 0x1b,
                (byte) 0x1c,
                (byte) 0x1d,
                (byte) 0x1e,
                (byte) 0x1f,
                (byte) 0x20,
                (byte) 0x21,
                (byte) 0x22,
                (byte) 0x23,
                (byte) 0x24,
                (byte) 0x25,
                (byte) 0x26,
                (byte) 0x27,
                (byte) 0x28,
                (byte) 0x29,
                (byte) 0x2a,
                (byte) 0x2b,
                (byte) 0x2c,
                (byte) 0x2d,
                (byte) 0x2e,
                (byte) 0x2f,
                (byte) 0x30,
                (byte) 0x31,
                (byte) 0x32,
                (byte) 0x33,
                (byte) 0x34,
                (byte) 0x35,
                (byte) 0x36,
                (byte) 0x37,
                (byte) 0x38,
                (byte) 0x39,
                (byte) 0x3a,
                (byte) 0x3b,
                (byte) 0x3c,
                (byte) 0x3d,
                (byte) 0x3e,
                (byte) 0x3f,
                (byte) 0x40,
                (byte) 0x41,
                (byte) 0x42,
                (byte) 0x43,
                (byte) 0x44,
                (byte) 0x45,
                (byte) 0x46,
                (byte) 0x47,
                (byte) 0x48,
                (byte) 0x49,
                (byte) 0x4a,
                (byte) 0x4b,
                (byte) 0x4c,
                (byte) 0x4d,
                (byte) 0x4e,
                (byte) 0x4f,
                (byte) 0x50,
                (byte) 0x51,
                (byte) 0x52,
                (byte) 0x53,
                (byte) 0x54,
                (byte) 0x55,
                (byte) 0x56,
                (byte) 0x57,
                (byte) 0x58,
                (byte) 0x59,
                (byte) 0x5a,
                (byte) 0x5b,
                (byte) 0x5c,
                (byte) 0x5d,
                (byte) 0x5e,
                (byte) 0x5f,
                (byte) 0x60,
                (byte) 0x61,
                (byte) 0x62,
                (byte) 0x63,
                (byte) 0x64,
                (byte) 0x65,
                (byte) 0x66,
                (byte) 0x67,
                (byte) 0x68,
                (byte) 0x69,
                (byte) 0x6a,
                (byte) 0x6b,
                (byte) 0x6c,
                (byte) 0x6d,
                (byte) 0x6e,
                (byte) 0x6f,
                (byte) 0x70,
                (byte) 0x71,
                (byte) 0x72,
                (byte) 0x73,
                (byte) 0x74,
                (byte) 0x75,
                (byte) 0x76,
                (byte) 0x77,
                (byte) 0x78,
                (byte) 0x79,
                (byte) 0x7a,
                (byte) 0x7b,
                (byte) 0x7c,
                (byte) 0x7d,
                (byte) 0x7e,
                (byte) 0x7f,
                (byte) 0x80,
                (byte) 0x81,
                (byte) 0x82,
                (byte) 0x83,
                (byte) 0x84,
                (byte) 0x85,
                (byte) 0x86,
                (byte) 0x87,
                (byte) 0x88,
                (byte) 0x89,
                (byte) 0x8a,
                (byte) 0x8b,
                (byte) 0x8c,
                (byte) 0x8d,
                (byte) 0x8e,
                (byte) 0x8f,
                (byte) 0x90,
                (byte) 0x91,
                (byte) 0x92,
                (byte) 0x93,
                (byte) 0x94,
                (byte) 0x95,
                (byte) 0x96,
                (byte) 0x97,
                (byte) 0x98,
                (byte) 0x99,
                (byte) 0x9a,
                (byte) 0x9b,
                (byte) 0x9c,
                (byte) 0x9d,
                (byte) 0x9e,
                (byte) 0x9f,
                (byte) 0xa0,
                (byte) 0xa1,
                (byte) 0xa2,
                (byte) 0xa3,
                (byte) 0xa4,
                (byte) 0xa5,
                (byte) 0xa6,
                (byte) 0xa7,
                (byte) 0xa8,
                (byte) 0xa9,
                (byte) 0xaa,
                (byte) 0xab,
                (byte) 0xac,
                (byte) 0xad,
                (byte) 0xae,
                (byte) 0xaf,
                (byte) 0xb0,
                (byte) 0xb1,
                (byte) 0xb2,
                (byte) 0xb3,
                (byte) 0xb4,
                (byte) 0xb5,
                (byte) 0xb6,
                (byte) 0xb7,
                (byte) 0xb8,
                (byte) 0xb9,
                (byte) 0xba,
                (byte) 0xbb,
                (byte) 0xbc,
                (byte) 0xbd,
                (byte) 0xbe,
                (byte) 0xbf,
                (byte) 0xc0,
                (byte) 0xc1,
                (byte) 0xc2,
                (byte) 0xc3,
                (byte) 0xc4,
                (byte) 0xc5,
                (byte) 0xc6,
                (byte) 0xc7,
                (byte) 0xc8,
                (byte) 0xc9,
                (byte) 0xca,
                (byte) 0xcb,
                (byte) 0xcc,
                (byte) 0xcd,
                (byte) 0xce,
                (byte) 0xcf,
                (byte) 0xd0,
                (byte) 0xd1,
                (byte) 0xd2,
                (byte) 0xd3,
                (byte) 0xd4,
                (byte) 0xd5,
                (byte) 0xd6,
                (byte) 0xd7,
                (byte) 0xd8,
                (byte) 0xd9,
                (byte) 0xda,
                (byte) 0xdb,
                (byte) 0xdc,
                (byte) 0xdd,
                (byte) 0xde,
                (byte) 0xdf,
                (byte) 0xe0,
                (byte) 0xe1,
                (byte) 0xe2,
                (byte) 0xe3,
                (byte) 0xe4,
                (byte) 0xe5,
                (byte) 0xe6,
                (byte) 0xe7,
                (byte) 0xe8,
                (byte) 0xe9,
                (byte) 0xea,
                (byte) 0xeb,
                (byte) 0xec,
                (byte) 0xed,
                (byte) 0xee,
                (byte) 0xef,
                (byte) 0xf0,
                (byte) 0xf1,
                (byte) 0xf2,
                (byte) 0xf3,
                (byte) 0xf4,
                (byte) 0xf5,
                (byte) 0xf6,
                (byte) 0xf7,
                (byte) 0xf8,
                (byte) 0xf9,
                (byte) 0xfa,
                (byte) 0xfb,
                (byte) 0xfc,
                (byte) 0xfd,
                (byte) 0xfe,
                (byte) 0xff,
                (byte) 0x00,
                (byte) 0x01,
                (byte) 0x02,
                (byte) 0x03,
                (byte) 0x04,
                (byte) 0x05,
                (byte) 0x06,
                (byte) 0x07,
                (byte) 0x08,
                (byte) 0x09,
                (byte) 0x0a,
                (byte) 0x0b,
                (byte) 0x0c,
                (byte) 0x0d,
                (byte) 0x0e,
                (byte) 0x0f,
                (byte) 0x10,
                (byte) 0x11,
                (byte) 0x12,
                (byte) 0x13,
                (byte) 0x14,
                (byte) 0x15,
                (byte) 0x16,
                (byte) 0x17,
                (byte) 0x18,
                (byte) 0x19,
                (byte) 0x1a,
                (byte) 0x1b,
                (byte) 0x1c,
                (byte) 0x1d,
                (byte) 0x1e,
                (byte) 0x1f,
                (byte) 0x20,
                (byte) 0x21,
                (byte) 0x22,
                (byte) 0x23,
                (byte) 0x24,
                (byte) 0x25,
                (byte) 0x26,
                (byte) 0x27,
                (byte) 0x28,
                (byte) 0x29,
                (byte) 0x2a,
                (byte) 0x2b,
                (byte) 0x2c,
                (byte) 0x2d,
                (byte) 0x2e,
                (byte) 0x2f,
                (byte) 0x30,
                (byte) 0x31,
                (byte) 0x32,
                (byte) 0x33,
                (byte) 0x34,
                (byte) 0x35,
                (byte) 0x36,
                (byte) 0x37,
                (byte) 0x38,
                (byte) 0x39,
                (byte) 0x3a,
                (byte) 0x3b,
                (byte) 0x3c,
                (byte) 0x3d,
                (byte) 0x3e,
                (byte) 0x3f,
                (byte) 0x40,
                (byte) 0x41,
                (byte) 0x42,
                (byte) 0x43,
                0x0c,
                0x02,
                (byte) 0x00,
                (byte) 0x7e,
                0x0d,
                0x02,
                (byte) 0x00,
                (byte) 0x01,
                0x0e,
                0x01,
                (byte) 0x30
            };

    @Test
    public void parseTagsMany() throws KlvParseException {
        List<LdsField> fields = getFields(manyTagsBytes);
        LegacyIQLocalSet localSet = LegacyIQLocalSet.fromST1108_2Fields(fields, manyTagsBytes);
        assertNotNull(localSet);
        assertEquals(localSet.displayHeader(), "ST 1108 Legacy Interpretability and Quality");
        assertEquals(localSet.getUniversalLabel(), KlvConstants.InterpretabilityQualityLocalSetUl);
        assertEquals(localSet.getIdentifiers().size(), 14);
        checkManyValues(localSet);
        assertEquals(localSet.frameMessage(false), manyTagsBytes);
    }

    @Test
    public void fromValuesMany() throws KlvParseException {
        Map<LegacyIQMetadataKey, IInterpretabilityQualityMetadataValue> values = new TreeMap<>();
        values.put(
                LegacyIQMetadataKey.MostRecentFrameTime,
                new MostRecentFrameTime(new ST0603TimeStamp(9)));
        values.put(LegacyIQMetadataKey.VideoInterpretability, new VideoInterpretability(6));
        values.put(LegacyIQMetadataKey.VideoQuality, new VideoQuality(96));
        values.put(LegacyIQMetadataKey.InterpretabilityQualityMethod, new QualityMethod(0));
        values.put(LegacyIQMetadataKey.PSNRCoefficientIdentifier, new PSNRCoefficientIdentifier(2));
        values.put(
                LegacyIQMetadataKey.QualityCoefficientIdentifier,
                new QualityCoefficientIdentifier(4));
        values.put(LegacyIQMetadataKey.RatingDuration, new RatingDuration(640));
        values.put(
                LegacyIQMetadataKey.MIQPakInsertionTime,
                new MIQPakInsertionTime(new ST0603TimeStamp(32)));
        values.put(
                LegacyIQMetadataKey.ChipLocationSizeBitDepth,
                new ChipLocationSizeBitDepth(87, 346, 32, 8));
        values.put(
                LegacyIQMetadataKey.ChipYvaluesUncompressed,
                new ChipValuesUncompressed(fillByteArray(1024)));
        values.put(LegacyIQMetadataKey.ChipYvaluesPNG, new ChipValuesPNG(fillByteArray(324)));
        values.put(LegacyIQMetadataKey.ChipEdgeIntensity, new ChipEdgeIntensity(126));
        values.put(LegacyIQMetadataKey.ChipFrequencyRatio, new ChipFrequencyRatio(1));
        values.put(LegacyIQMetadataKey.ChipPSNR, new ChipPSNR(48));
        LegacyIQLocalSet localSet = new LegacyIQLocalSet(values);
        assertNotNull(localSet);
        assertEquals(localSet.displayHeader(), "ST 1108 Legacy Interpretability and Quality");
        assertEquals(localSet.getUniversalLabel(), KlvConstants.InterpretabilityQualityLocalSetUl);
        assertEquals(localSet.getIdentifiers().size(), 14);
        checkManyValues(localSet);
        assertEquals(localSet.frameMessage(false), manyTagsBytes);
    }

    private void checkManyValues(LegacyIQLocalSet localSet) {
        checkMostRecentFrameTime(localSet);
        checkInterpretability(localSet);
        checkVideoQuality(localSet);
        checkMethod(localSet);
        checkPSNRCoefficientId(localSet);
        checkQualityCoefficientId(localSet);
        checkRatingDuration(localSet);
        checkMIQPakInsertionTime(localSet);
        checkChipLocationSizeBitDepth(localSet);
        checkChipValuesUncompressed(localSet);
        checkChipValuesPNG(localSet);
        checkChipEdgeIntensity(localSet);
        checkChipFrequencyRatio(localSet);
        checkChipPSNR(localSet);
    }

    public static void checkMostRecentFrameTime(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.MostRecentFrameTime));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.MostRecentFrameTime);
        assertTrue(value instanceof MostRecentFrameTime);
        MostRecentFrameTime uut = (MostRecentFrameTime) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Most Recent Frame Time");
        assertEquals(uut.getDisplayableValue(), "9");
        assertEquals(uut.getTime().getMicroseconds(), 9);
    }

    private void checkInterpretability(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.VideoInterpretability));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.VideoInterpretability);
        assertTrue(value instanceof VideoInterpretability);
        VideoInterpretability uut = (VideoInterpretability) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Video Interpretability");
        assertEquals(uut.getDisplayableValue(), "6");
        assertEquals(uut.getInterpretability(), 6);
    }

    private void checkVideoQuality(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.VideoQuality));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.VideoQuality);
        assertTrue(value instanceof VideoQuality);
        VideoQuality uut = (VideoQuality) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Video Quality");
        assertEquals(uut.getDisplayableValue(), "96");
        assertEquals(uut.getQuality(), 96);
    }

    private void checkMethod(LegacyIQLocalSet localSet) {
        assertTrue(
                localSet.getIdentifiers()
                        .contains(LegacyIQMetadataKey.InterpretabilityQualityMethod));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.InterpretabilityQualityMethod);
        assertTrue(value instanceof QualityMethod);
        QualityMethod uut = (QualityMethod) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Interpretability Quality Method");
        assertEquals(uut.getDisplayableValue(), "0 (Manual)");
        assertEquals(uut.getMethodId(), 0);
    }

    private void checkPSNRCoefficientId(LegacyIQLocalSet localSet) {
        assertTrue(
                localSet.getIdentifiers().contains(LegacyIQMetadataKey.PSNRCoefficientIdentifier));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.PSNRCoefficientIdentifier);
        assertTrue(value instanceof PSNRCoefficientIdentifier);
        PSNRCoefficientIdentifier uut = (PSNRCoefficientIdentifier) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "PSNR Coefficient Identifier");
        assertEquals(uut.getDisplayableValue(), "2");
        assertEquals(uut.getIdentifier(), 2);
    }

    private void checkQualityCoefficientId(LegacyIQLocalSet localSet) {
        assertTrue(
                localSet.getIdentifiers()
                        .contains(LegacyIQMetadataKey.QualityCoefficientIdentifier));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.QualityCoefficientIdentifier);
        assertTrue(value instanceof QualityCoefficientIdentifier);
        QualityCoefficientIdentifier uut = (QualityCoefficientIdentifier) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Quality Coefficient Identifier");
        assertEquals(uut.getDisplayableValue(), "4");
        assertEquals(uut.getIdentifier(), 4);
    }

    private void checkRatingDuration(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.RatingDuration));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.RatingDuration);
        assertTrue(value instanceof RatingDuration);
        RatingDuration uut = (RatingDuration) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Rating Duration");
        assertEquals(uut.getDisplayableValue(), "640 frames");
        assertEquals(uut.getDuration(), 640);
    }

    private void checkMIQPakInsertionTime(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.MIQPakInsertionTime));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.MIQPakInsertionTime);
        assertTrue(value instanceof MIQPakInsertionTime);
        MIQPakInsertionTime uut = (MIQPakInsertionTime) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Insertion Time");
        assertEquals(uut.getDisplayableValue(), "32");
        assertEquals(uut.getTime().getMicroseconds(), 32);
    }

    private void checkChipLocationSizeBitDepth(LegacyIQLocalSet localSet) {
        assertTrue(
                localSet.getIdentifiers().contains(LegacyIQMetadataKey.ChipLocationSizeBitDepth));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.ChipLocationSizeBitDepth);
        assertTrue(value instanceof ChipLocationSizeBitDepth);
        ChipLocationSizeBitDepth uut = (ChipLocationSizeBitDepth) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Chip Location, Size & Bit Depth");
        assertEquals(uut.getDisplayableValue(), "[87, 346], 32x32, 8");
        assertEquals(uut.getColumnIndex(), 87);
        assertEquals(uut.getRowIndex(), 346);
        assertEquals(uut.getChipLength(), 32);
        assertEquals(uut.getBitDepth(), 8);
    }

    private void checkChipValuesUncompressed(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.ChipYvaluesUncompressed));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.ChipYvaluesUncompressed);
        assertTrue(value instanceof ChipValuesUncompressed);
        ChipValuesUncompressed uut = (ChipValuesUncompressed) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Chip Y-values Uncompressed");
        assertEquals(uut.getDisplayableValue(), "1024 bytes");
        assertEquals(uut.getBytes().length, 1024);
    }

    private void checkChipValuesPNG(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.ChipYvaluesPNG));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.ChipYvaluesPNG);
        assertTrue(value instanceof ChipValuesPNG);
        ChipValuesPNG uut = (ChipValuesPNG) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Chip Y-values PNG");
        assertEquals(uut.getDisplayableValue(), "324 bytes");
        assertEquals(uut.getBytes().length, 324);
    }

    private void checkChipEdgeIntensity(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.ChipEdgeIntensity));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.ChipEdgeIntensity);
        assertTrue(value instanceof ChipEdgeIntensity);
        ChipEdgeIntensity uut = (ChipEdgeIntensity) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Chip Edge Intensity");
        assertEquals(uut.getDisplayableValue(), "126");
        assertEquals(uut.getIntensity(), 126);
    }

    private void checkChipFrequencyRatio(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.ChipFrequencyRatio));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.ChipFrequencyRatio);
        assertTrue(value instanceof ChipFrequencyRatio);
        ChipFrequencyRatio uut = (ChipFrequencyRatio) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Chip Frequency Ratio");
        assertEquals(uut.getDisplayableValue(), "1");
        assertEquals(uut.getRatio(), 1);
    }

    private void checkChipPSNR(LegacyIQLocalSet localSet) {
        assertTrue(localSet.getIdentifiers().contains(LegacyIQMetadataKey.ChipPSNR));
        IKlvValue value = localSet.getField(LegacyIQMetadataKey.ChipPSNR);
        assertTrue(value instanceof ChipPSNR);
        ChipPSNR uut = (ChipPSNR) value;
        assertNotNull(uut);
        assertEquals(uut.getDisplayName(), "Chip PSNR");
        assertEquals(uut.getDisplayableValue(), "48 dB");
        assertEquals(uut.getPSNR(), 48);
    }

    @Test(expectedExceptions = IllegalArgumentException.class)
    public void badNesting() throws KlvParseException {
        List<LdsField> fields = getFields(manyTagsBytes);
        LegacyIQLocalSet localSet = LegacyIQLocalSet.fromST1108_2Fields(fields, manyTagsBytes);
        localSet.frameMessage(true);
    }

    private byte[] fillByteArray(int length) {
        byte[] bytes = new byte[length];
        for (int i = 0; i < length; i++) {
            bytes[i] = (byte) (i % 256);
        }
        return bytes;
    }
}
