package org.jmisb.mimd.v1.st1903;

import static org.testng.Assert.*;

import org.jmisb.api.common.KlvParseException;
import org.jmisb.mimd.IMimdMetadataValue;
import org.jmisb.mimd.v1.st1902.LoggerChecks;
import org.testng.annotations.Test;

/**
 * Additional unit tests for MIMD.
 *
 * <p>These are different between MIMD versions, so not autogenerated.
 */
public class AdditionalMIMDTest extends LoggerChecks {

    public AdditionalMIMDTest() {
        super(MIMD.class);
    }

    @Test
    public void parseFromBytesMimdId() throws KlvParseException {
        byte[] bytes =
                new byte[] {
                    0x06,
                    0x0E,
                    0x2B,
                    0x34,
                    0x02,
                    0x05,
                    0x01,
                    0x01,
                    0x0E,
                    0x01,
                    0x05,
                    0x03,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x06,
                    0x01,
                    0x02,
                    0x04,
                    0x03,
                    (byte) 0xbb,
                    (byte) 0xd4
                };
        verifyNoLoggerMessages();
        MIMD uut = new MIMD(bytes);
        verifyNoLoggerMessages();
        assertEquals(uut.getBytes(), bytes);
        assertNotNull(uut.getIdentifiers());
        assertEquals(uut.getIdentifiers().size(), 1);
        assertNotNull(uut.getField(MIMDMetadataKey.mimdId));
    }

    @Test(expectedExceptions = KlvParseException.class)
    public void parseFromBytesBadValue() throws KlvParseException {
        new MIMD(
                new byte[] {
                    0x06,
                    0x0E,
                    0x2B,
                    0x34,
                    0x02,
                    0x05,
                    0x01,
                    0x01,
                    0x0E,
                    0x01,
                    0x05,
                    0x03,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x05,
                    0x01,
                    0x01,
                    (byte) 0x81,
                    (byte) 0xc6,
                    (byte) 0x8f
                });
    }

    @Test
    public void parseFromBytesBadTag() throws KlvParseException {
        verifyNoLoggerMessages();
        IMimdMetadataValue uut =
                new MIMD(
                        new byte[] {
                            0x06, 0x0E, 0x2B, 0x34, 0x02, 0x05, 0x01, 0x01, 0x0E, 0x01, 0x05, 0x03,
                            0x00, 0x00, 0x00, 0x00, 0x09, 0x7F, 0x01, 0x00, 0x01, 0x02, 0x04, 0x03,
                            0x59, 0x4d
                        });
        verifySingleLoggerMessage("Unknown MIMD Metadata id: 127");
        assertEquals(
                uut.getBytes(),
                new byte[] {
                    0x06,
                    0x0E,
                    0x2B,
                    0x34,
                    0x02,
                    0x05,
                    0x01,
                    0x01,
                    0x0E,
                    0x01,
                    0x05,
                    0x03,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x06,
                    0x01,
                    0x02,
                    0x04,
                    0x03,
                    (byte) 0xbb,
                    (byte) 0xd4
                });
    }
}
