/**
 * ST 1301: Motion Imagery Identification System (MIIS) - Augmentation Identifiers.
 *
 * <p>Motion imagery data is generated by many different sensors, distributed across many different
 * networks and received by many different users and systems. To coordinate analysis, manage and
 * generally prevent confusion with such a large number of motion imagery sources it is important to
 * define a consistent name or identity for each source along with supplemental identifiers for
 * various purposes. The Motion Imagery Identification System (MIIS) is a pair of Standards – ST
 * 1204 and ST 1301. ST 1204 defines the consistent name of the source and ST 1301 (this document)
 * defines the supplemental identifiers, called augmentation identifiers.
 *
 * <p>Please refer to MISB ST 1204 for the overview, scope and background of the MIIS.
 */
package org.jmisb.st1301;
