name: JDK11 Build (Ubuntu 20.04 default)

on:
    push:
      branches: [ develop, 2.x ]
    pull_request:
      branches: [ develop, 2.x ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build and install
        run: mvn -B install -Pdebug || mvn -B install -Pdebug || mvn -B install -Pdebug
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: >-
          ./api-awt/target/site/jacoco/jacoco.xml,
          ./api-ffmpeg/target/site/jacoco/jacoco.xml,
          ./api/target/site/jacoco/jacoco.xml,
          ./core/target/site/jacoco/jacoco.xml,
          ./eg0104/target/site/jacoco/jacoco.xml,
          ./mimd/target/site/jacoco/jacoco.xml,
          ./st0102/target/site/jacoco/jacoco.xml,
          ./st0601/target/site/jacoco/jacoco.xml,
          ./st0602/target/site/jacoco/jacoco.xml,
          ./st0805/target/site/jacoco/jacoco.xml,
          ./st0808/target/site/jacoco/jacoco.xml,
          ./st0809/target/site/jacoco/jacoco.xml,
          ./st1108/target/site/jacoco/jacoco.xml,
          ./st1206/target/site/jacoco/jacoco.xml,
          ./st1301/target/site/jacoco/jacoco.xml,
          ./st1403/target/site/jacoco/jacoco.xml,
          ./st1603/target/site/jacoco/jacoco.xml,
          ./st1909/target/site/jacoco/jacoco.xml


