name: JDK11 Build (Ubuntu 20.04 default)

on:
    push:
      branches: [ develop ]
    pull_request:
      branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Build and check dependencies
        run: mvn -B install --file pom.xml

