name: JDK11 Build (Ubuntu 20.04 default)

on:
    push:
      branches: [ develop, 2.x ]
    pull_request:
      branches: [ develop, 2.x ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build and install
        run: mvn -B install -Pdebug || mvn -B install -Pdebug || mvn -B install -Pdebug
      - name: Upload core test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./core/target/site/jacoco/jacoco.xml
          flags: unittests-core
      - name: Upload api test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./api/target/site/jacoco/jacoco.xml
          flags: unittests-api
      - name: Upload api-awt test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./api-awt/target/site/jacoco/jacoco.xml
          flags: unittests-awt
      - name: Upload api-ffmpeg test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./api-ffmpeg/target/site/jacoco/jacoco.xml
          flags: unittests-api-ffmpeg
      - name: Upload ST 0601 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st0601/target/site/jacoco/jacoco.xml
          flags: unittests-st0601
      - name: Upload ST 0602 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st0602/target/site/jacoco/jacoco.xml
          flags: unittests-st0602
      - name: Upload ST 0805 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st0805/target/site/jacoco/jacoco.xml
          flags: unittests-st0805
      - name: Upload ST 0806 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st0806/target/site/jacoco/jacoco.xml
          flags: unittests-st0806
      - name: Upload ST 0808 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st0808/target/site/jacoco/jacoco.xml
          flags: unittests-st0808
      - name: Upload ST 0809 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st0809/target/site/jacoco/jacoco.xml
          flags: unittests-st0809
      - name: Upload ST 0903 VMTI implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st0903/target/site/jacoco/jacoco.xml
          flags: unittests-st0903-vmti
      - name: Upload ST 0903 VTrack implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st0903vtrack/target/site/jacoco/jacoco.xml
          flags: unittests-st0903-vtrack
      - name: Upload ST 1108 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st1108/target/site/jacoco/jacoco.xml
          flags: unittests-st1108
      - name: Upload ST 1206 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st1206/target/site/jacoco/jacoco.xml
          flags: unittests-st1206
      - name: Upload ST 1301 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st1301/target/site/jacoco/jacoco.xml
          flags: unittests-st1301
      - name: Upload ST 1403 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st1403/target/site/jacoco/jacoco.xml
          flags: unittests-st1403
      - name: Upload ST 1601 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st1601/target/site/jacoco/jacoco.xml
          flags: unittests-st1601
      - name: Upload ST 1602 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st1602/target/site/jacoco/jacoco.xml
          flags: unittests-st1602
      - name: Upload ST 1603 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st1603/target/site/jacoco/jacoco.xml
          flags: unittests-st1603
      - name: Upload ST 190x implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./mimd/target/site/jacoco/jacoco.xml
          flags: unittests-mimd
      - name: Upload ST 1909 implementation test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./st1909/target/site/jacoco/jacoco.xml
          flags: unittests-st1909
      - name: Upload geoid test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./elevation/geoid/target/site/jacoco/jacoco.xml
          flags: unittests-geoid


