name: JDK17 Build (Ubuntu 22.04)

on:
    push:
      branches: [ develop, 2.x ]
    pull_request:
      branches: [ develop, 2.x ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5
      - name: Build and install
        run: mvn -B install -Pdebug || mvn -B install -Pdebug || mvn -B install -Pdebug

