name: JDK11 Build (Ubuntu 20.04 default)

on:
    push:
      branches: [ develop, 2.x ]
    pull_request:
      branches: [ develop, 2.x ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build and install
        run: mvn -B install -Pdebug || mvn -B install -Pdebug || mvn -B install -Pdebug
      - name: Upload core test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./core/target/site/jacoco/jacoco.xml
          flags: unittests-core
      - name: Upload api test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./api/target/site/jacoco/jacoco.xml
          flags: unittests-api
      - name: Upload api-ffmpeg test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./api-ffmpeg/target/site/jacoco/jacoco.xml
          flags: unittests-api-ffmpeg
      - name: Upload geoid test results to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: ./elevation/geoid/target/site/jacoco/jacoco.xml
          flags: unittests-geoid


