name: Linux Build - JDK 8

on:
    push:
      branches: [ develop ]
    pull_request:
      branches: [ develop ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
      - name: Build and test
        run: mvn --batch-mode --update-snapshots verify

